version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run: echo "build"
  test1:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run: echo "test1"
  deploy-prod:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run: echo "deploying..."

workflows:
  version: 2
  build_test_approve:
    jobs:
      - build
      - test1
      - deploy-prod-approval:
          type: approval
          requires:
            - build
            - test1
      - deploy-prod:
          requires:
            - deploy-prod-approval
