version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run: echo "build"
  test1:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run: echo "test1"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
  deploy-prod:
    type: approval
    requires:
      - build_and_test
